
name: Release touch1200bps
on:
  workflow_dispatch: # trigger manually
jobs:   
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build distribution tarballs
        run: make dist1200bps
      - name: Create release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          artifacts: "dist/*.tgz"
          omitBody: true
